name: remind review
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "bossm0n5t3r"
      home:
        description: "location"
        required: false
        default: "The Octoverse"
  schedule:
    - cron: '0 15 * * *'
jobs:
  send_pull_requests:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: listPullRequests
        uses: buildsville/list-pull-requests@v1
        id: list
        with:
          token: ${{secrets.TOKEN}}
          labels: '["dependencies"]'
          skip_hour: '0'
      - name: output
        run: echo '${{ steps.list.outputs.pulls }}'
