name: remind review
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "bossm0n5t3r"
      home:
        description: "location"
        required: false
        default: "The Octoverse"
  schedule:
    - cron: '0 15 * * *'
jobs:
  send_pull_requests:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/github-script@v6
        id: create-combined-pr
        name: Create Combined PR
        with:
          github-token: ${{secrets.TOKEN}}
          script: |
            const owner = context.repo.owner
            console.log(owner)
            const pulls = await github.paginate(`GET /repos/:owner/:repo/pulls`, {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
