name: remind review
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "bossm0n5t3r"
      home:
        description: "location"
        required: false
        default: "The Octoverse"
  schedule:
    - cron: '0 15 * * *'
jobs:
  send_pull_requests:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/github-script@v6
        id: create-combined-pr
        name: Create Combined PR
        with:
          github-token: ${{secrets.TOKEN}}
          script: |
            const prs = await github.paginate(`GET /repos/:owner/:repo/pulls`, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });
            
            let prsByCreateDependabot = [];
            let baseBranch = null;
            let baseBranchSHA = null;
            
            for (const pr of prs) {
              const branch = pr[`head`][`ref`];
              
              if (branch.startsWith('dependabot')) {
                prsByCreateDependabot.push(pr);
                baseBranch = pr[`base`][`ref`]
                baseBranchSHA = pr['base']['sha'];
              }
            }
            
            await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/heads/dependabot:testete',
                sha: baseBranchSHA
              });
            
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,                
              title: 'Combined Dependabot PR',
              head: 'dependabot:testete',
              base: baseBranch
            });
            
            for (const pr of prsByCreateDependabot) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                state: "closed"
              });
            }
          
